Перейти к содержимому
андрейбиоазум-клетка
Кубическая Битва-3
Навигация по репозиторию
Код
Проблемы
Запросы на слияние
Действия
Проекты
Вики
Безопасность и качество
Build Cubic Battle Android
Обновите файл android-build.yml #576
Все вакансии
Подробности выполнения
Аннотации
1 ошибка и 1 предупреждение
строить
неуспешный сейчасв 14 секундах
Журналы поиска
2с
1с
9s
Запустите actions/setup-java@v5
Установленные дистрибутивы
Создание файла settings.xml с server-id: github
Запись в файл /home/runner/.m2/settings.xml
Настроил MAVEN_ARGS, добавив параметр -ntp для подавления логов хода передачи Maven. Установил 'show-download-progress: true', чтобы сохранить вывод хода загрузки.
Ошибка: В каталоге /home/runner/work/Cubic-Battle-3/Cubic-Battle-3 не найден файл, соответствующий [**/*.gradle*,**/gradle-wrapper.properties,buildSrc/**/Versions.kt,buildSrc/**/Dependencies.kt,gradle/*.versions.toml,**/versions.properties]. Убедитесь, что вы переключились на целевой репозиторий.
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
0 с
